### ISSUE TITLE
Pass custom parameters to eth_call

### ISSUE THREAD

**Issue by aymanelya** [dopex-io/web3-multicall#2]
I'm wondering if there's any way to pass custom parameters to the aggregate function

example:
.call({from: "0x00000"})

**Comment by witherblock** [comment]
Not sure why this is required but adding it in the 0.1.7 release

**Comment by witherblock** [comment]
Published in 0.1.7

Added in commit - https://github.com/dopex-io/web3-multicall/commit/ac59d6f4e960776ff5a7eb6524973b1befe42144
