### ISSUE TITLE
[Error] Submitting an calling array to multicall contract, it seems reverts all that renders not to go further away

### ISSUE THREAD

**Issue by sigridjineth** [dopex-io/web3-multicall#5]
## Error Statusquo
* When submitting a call array in a multicall contract, even if just one of the arrays is reverted, the whole multicall gets reverted. This is the problem I'm trying to tackle.

```
[tokenAName, tokenADecimal, tokenBName, tokenBDecimal] = await multicall.aggregate([
  tokenAContract.methods.symbol(),
  tokenAContract.methods.decimals(),
  tokenBContract.methods.symbol(),
  tokenBContract.methods.decimals(),
]);
```
* The error phenomenon is as follows when using require in solidity code,
```Error: Returned error: evm: execution reverted```
* The following error occurs when `require` is removed.
```
Error: Returned values ​​aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
```

## Workaround
* it would be able to avoid the problem by using `try-catch` statement, since `call` returns `false` value to direct the code into `catch` condition.
* Is there any proper way to solve the problem? The aformentioned approach seems a stopgap to me.

**Comment by masquel** [comment]
@jypthemiracle hey, please checkout https://github.com/HashEx/web3-multicall it has a workaround in contract for failed requests inside smart contract

**Comment by jypthemiracle** [comment]
@masquel hey, thanks for your kind reply. do not understand what the difference between `call` and `staticcall` - can you explain more? highly appreciated.

**Comment by witherblock** [comment]
> @jypthemiracle hey, please check out https://github.com/HashEx/web3-multicall it has a workaround for failed requests inside smart contract

Seems like the code is a copy paste of this repo without any giving any credits.

**Comment by witherblock** [comment]
> ## Error Statusquo
> * When submitting a call array in a multicall contract, even if just one of the arrays is reverted, the whole multicall gets reverted. This is the problem I'm trying to tackle.
> 
> ```
> [tokenAName, tokenADecimal, tokenBName, tokenBDecimal] = await multicall.aggregate([
>   tokenAContract.methods.symbol(),
>   tokenAContract.methods.decimals(),
>   tokenBContract.methods.symbol(),
>   tokenBContract.methods.decimals(),
> ]);
> ```
> 
> * The error phenomenon is as follows when using require in solidity code,
>   `Error: Returned error: evm: execution reverted`
> * The following error occurs when `require` is removed.
> 
> ```
> Error: Returned values ​​aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
> ```
> 
> ## Workaround
> * it would be able to avoid the problem by using `try-catch` statement, since `call` returns `false` value to direct the code into `catch` condition.
> * Is there any proper way to solve the problem? The aformentioned approach seems a stopgap to me.

The contract would need to handle that internally

**Comment by masquel** [comment]
@witherblock now that repo is made like a fork from yours. Also we mentioned your library in our article - https://blog.hashex.org/multicall-analytex-approach-to-data-processing-978f81185db6

@jypthemiracle the workaround we used is contract doesn't require a success response during a call, but you need to handle it now by yourself. `call` function can change contract state, `staticcall` can't. So it's better to use `staticcall` in mulitcall if you plan only to read values, not to write.

**Comment by witherblock** [comment]
Okay thanks, closing this issue.
